### PR TITLE
Add de.json translation

### PR DESCRIPTION
**Pull request by Dielee**

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks! I'll need to cherry pick this as you have a commit deleting the en.json

**Comment by alandtse** [comment]
Ok I merged it in manually. Thanks again!

**Comment by Dielee** [comment]
There is missing an 'e':
` "description": "**{email} - alexa.{url}**\nBitte Verifizierungs Method auswählen. (z.B., `sms` oder `email`)\n{message}",`

This should be:
 "description": "**{email} - alexa.{url}**\nBitte Verifizierungs Methode auswählen. (z.B., `sms` oder `email`)\n{message}",

sorry for this.

**Comment by alandtse** [comment]
Got it. Thanks!

**Pull request closed without merging**
