### PR TITLE
feat: add support for Amazon Smart Plug

### PR DESCRIPTION
**Pull request by alams154**
This feature allows the user to control Amazon Smart Plugs from the Alexa Media Player integration via switches in Home Assistant.

The feature is valuable since these devices cannot be added to Home Assistant and require complex workarounds.  For example, one implementation requires the use of various plugins used in conjunction (VoiceMonkey for routine triggers, Node-RED for state management and HTTP request methods, and Emulated Hue for state synchronization).

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. As a note this will be added after we raised minimum version to 2024.1.b0 so when I merge it you won't see it until you've updated.

**Review by alandtse — APPROVED** [review]

**Comment by alams154** [comment]
Sounds good, thanks for all the hard work!

**Comment by jvcsw** [comment]
Thanks, but how it works?

**Comment by alams154** [comment]
> Thanks, but how it works?

image

Make sure you have "Include devices connected via Echo" enabled.  If your Amazon Smart Plug is correctly setup with your Amazon account on the Alexa app, the plug should automatically be discovered as a switch.  It will show up as a switch entity under the integration.

image

**Comment by saberstop** [comment]
Hello, awesome work! At this point is the state of the plug expected to be working? I find that I am able to control the smart plug, but it won't actually update the state in Home Assistant if I use something other than HA like Alexa to turn on/off the plug. Thanks!

**Comment by alams154** [comment]
Yep, I noticed that yesterday that the state wasn’t working.  I have some ideas on how to fix that which I’ll try implementing tomorrow.  I’m pretty new to Home Assistant development so I’m learning as I go.  I think the same problem exists with lights added by Alexa Media Player too, which is where I got my implementation from.

I think the main thing is the entity is missing an update/async_update function.  Depending on how the AlexaApy and Alexa handles state changes it might have a decent amount of delay in state changes.

I’m basing this off of the Wyze HACS integration which has about a 20 second delay from when you change it in Wyze and when you see the change in Home Assistant.

**Comment by IceBotYT** [comment]
I know this is late, but thank you so much for this! I've just had this smart plug lying on my shelf for over a year now so to see it working finally is so satisfying to see. Can't wait to make more automations with it!!

**Comment by NonaSuomy** [comment]
does this work with amazon light switches/dimmers as well?

**Pull request merged**
