### PR TITLE
fix: fix hass_url undefined

### LINKED ISSUE #2408: config_flow.py line 815: `hass_url` undefined
Sorry everyone but I just had an automatic re-auth situation which triggered the `update_schema_defaults `and unfortunately there was a pre-existing `self.config.pop("hass_url")` at line 621 in `async def _test_login` making `hass_url `unavailable after that.

I removed lines 621-622, restarted and the problem was resolved.

Issuing a new PR for it...

### PR DESCRIPTION
**Pull request by danielbrunt57**
Removed self.config.pop("hass_url")
Fixes #2408

### CODE REVIEW

**Review by LorenzoRogai — APPROVED** [review]

**Comment by chrisvblemos** [comment]
@danielbrunt57 Could you also include the following change to this PR as described by @LorenzoRogai [here](https://github.com/alandtse/alexa_media_player/issues/2408#issuecomment-2274440500)? 

Can't get more undefined than that.

**Comment by chrisvblemos** [comment]
I'm not sure yet why this pop was there to begin with and can't comment on whether removing it could break other things. I think the root issue is at line 815. Solution is very simple, as given by @LorenzoRogai, and should be included anyway even if the .pop is unnecessary as it is a critical error (hass_url doesn't exist in the given context):

Change
`CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)`
to:
`CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, DEFAULT_HASS_URL)`

**Comment by danielbrunt57** [comment]
I've compared v4.12.5 with v4.10.3 and in 4.10.3, `hass_url `was never in `_update_schema_defaults`:
```
                vol.Required(
                    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                ): str,
```
I think I added it with the intention it be a reconfigurable option but after a little discussion with Alan, decided to not make it reconfigurable and that section of code lingered.  I've tested my `config_flow` leaving lines 620-621 with `config.pop` in `_test_login` as they were previously but removed lines 814-816 in `_update_schema_defaults`.  Initial configuration worked and also a reconfigure options so I believe at this point, that is the correct fix.

**Comment by grantclem** [comment]
Sadly not working for .com.au

**Pull request merged**
