### PR TITLE
fix: update strings.json

### PR DESCRIPTION
**Pull request by danielbrunt57**
- Removed: services: clear_history
- Changed: miscellaneous wording changes

### CODE REVIEW

**Comment by alandtse** [comment]
This seems to be tied to another PR if you're introducing a warning `deprecated_yaml_configuration`.

**Comment by danielbrunt57** [comment]
Yes, it contains the strings addition required for PR [#2685]( https://github.com/alandtse/alexa_media_player/pull/2685)

**Comment by alandtse** [comment]
So changes should be atomic. So any string changes for that pr should be in the PR. You shouldn't require two PRs to get the effect.

**Comment by danielbrunt57** [comment]
Alright,  I'll amend both PR's then...

**Comment by danielbrunt57** [comment]
My thinking was that both PR's would be merged at the same time thus no harm.  Or the strings PR merged first then the deprecated PR following that, but I'll conform...

**Comment by alandtse** [comment]
Also, after the other one goes through, please explain why you're updating the strings better.  Update doesn't explain anything. If we needed to review this 3 months later, it doesn't explain what has changed any more than the fact a file has been changed. It forces someone to actually read the changes to guess what was intended.

**Comment by danielbrunt57** [comment]
If you prefer, I can cancel my PR for deprecate and let you merge strings.  Then I update my deprecate branch to your new dev and submit a new PR with new strings addition and config changes for deprecation...

**Comment by danielbrunt57** [comment]
I'm going to close this one as it is basically just cosmetic + remove a deprecated section.
I think it's more important to move forward on the yaml deprecation and the 4.13.8 reversion.

**Pull request closed without merging**
