### PR TITLE
fix: fix hass.component.group deprecation.

### PR DESCRIPTION
**Pull request by Petro31**
Fixes https://github.com/alandtse/alexa_media_player/issues/2247.

### CODE REVIEW

**Review by alandtse — APPROVED** [review]
Thanks, do we need to bump the min ha version to access that function?

**Comment by Petro31** [comment]
That's a good question, I'll look into it in the morning.

**Comment by Petro31** [comment]
Yes, the change to the function was made in 2024.2.0b0, so I assume this was added then.

https://github.com/home-assistant/core/pull/106924

**Comment by alandtse** [comment]
Can you also bump the minimum ha in hacs.json please?

**Pull request merged**
