### PR TITLE
fix: bump alexapy to version 1.29.5

### PR DESCRIPTION
**Pull request by bieniu**
Changelog: https://gitlab.com/keatontaylor/alexapy/-/releases/v1.29.5

Closes: #2723 
Closes: #2720
Closes: #2698

### CODE REVIEW

**Comment by fernandolcardoso** [comment]
Please approve it, lol

image

**Comment by daknightuk** [comment]
Amazing work for an integration which I use A LOT thanks guys for fixing the issue :)

**Comment by PJLLB** [comment]
I agree. I use and rely on this integration many, many times every day for everything from announcing open doors to freezers being over temperature. Thank you to those who maintain it.

**Comment by THW712** [comment]
Once again, I am very humbled by your expertise and brilliance. A huge thank you for all you do; your efforts really do make a significant difference to my quality of life.

**Comment by tciprop** [comment]
Brilliant work to rectify this so quickly. Many thanks.

**Pull request merged**
