### PR TITLE
feat: Add restore volume service (#2773)

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Comment by alandtse** [comment]
@danielbrunt57 Please note your strings.json is incomplete and is [breaking hassfest](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806).
```
Error: R] [SERVICES] Service restore_volume has no name and is not in the translations file
```

Please fix and submit a PR.

**Comment by danielbrunt57** [comment]
> @danielbrunt57 Please note your strings.json is incomplete and is [breaking hassfest](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806).
> 
> ```
> Error: R] [SERVICES] Service restore_volume has no name and is not in the translations file
> ```
> 
> Please fix and submit a PR.

I'm confused.  My `strings.json` has "restore_volume".  
I also had to modify `translations/en.json` as well for the checks to succeed.

image

image

**Comment by alandtse** [comment]
You don't have a name field.

**Comment by danielbrunt57** [comment]
Yes I do:
```
    "restore_volume": {
      "description": "Restore previous volume level on Alexa media player device",
      "fields": {
        "entity_id": {
          "description": "Entity to restore the previous volume level on",
          "name": "Select media player:"
        }
      },
      "name": "Restore Previous Volume"
    },
```

It's just not in the same order as the other two services.  Is that the reason for the error?

```
    "force_logout": {
      "name": "Force Logout",
      "description": "Force account to logout. Used mainly for debugging.",
      "fields": {
        "email": {
          "name": "Email address",
          "description": "Accounts to clear. Empty will clear all."
        }
      }
    },
```

**Comment by alandtse** [comment]
I don't know. Please figure it out. Hassfest breaking is a problem and I'll just revert the PR if it's not solved.

**Pull request merged**
