### PR TITLE
fix: fix infinite loop and memory exhaustion

### LINKED ISSUE #2579: Version v4.13.3 is making HA fail
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I installed v4.13.3 and shortly after my HA kept loosing connection.  I would re boot, it would work fine for a few minutes, then it would disconect.

**To Reproduce**

I used a full backup for HA for Sept 30th.  Before the Alexa update I did a core update, assumed that caused the issue.  Once I restored I didn't do the core update but did do the Alexa update.  Few minutes later issue of disconnect started again.

Restored the Sept 30th backup again. This time I did the HA core update, but skipped the v4.13.3 update for Alexa.  My HA has been stable for over 30 minutes now. 

**Expected behavior**

I would expect to install v4.13.3 and not have my HA system crash.

**Screenshots**

No screen shots

**System details**

- Home Assistant version: Running HA via proxmox server.  Updated to the last version
- alexa_media version (from `const.py` or HA startup log): Stable version 4.13.2
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

### PR DESCRIPTION
**Pull request by dpwood**
Iterate on a copy of the existing_serials rather than extend the list being iterated causing infinite iteration

Fixes #2579

### CODE REVIEW

**Comment by danielbrunt57** [comment]
@dpwood Are you aware of @jleinenbach's PR to address #2579?  
I was not having an issue with the original code (or even 4.13.3 for that matter) so I'm wondering what conditions are present for an infinite loop to occur...

**Comment by dpwood** [comment]
Aware of it but not tried it. It looked like an AI attempt at a solution rather than anything focused. A lot of changes that don't seem to address the actual problem. 

I was having the issue very reliably and the mistake seemed clear. This one line fix has resolved it for me.

Your question about conditions required for failure is a good one. I suspect number or types of Alexa devices is relevant? I'll do some more investigating.

**Comment by dpwood** [comment]
On startup the existing_serials is [], after a few minutes the function re-runs and in my case I have 17 entries before entering the loop, which is the number of devices I have.  I then see it enter an infinite loop and the existing_serials array grows indefinitely.

I suspect the precondition is having a device with an appDeviceList which is somehow self-referencing? The new way of adding to the list is potentially recursive.

**Comment by danielbrunt57** [comment]
The new code might be appending with a serial# vs without a serial# before? I suspect my environment (10 physical "included" Echo devices) might not have any appDeviceList entities. I wonder if it might be the Alexa App "device", which I've excluded (by not including it)...

**Comment by dpwood** [comment]
I don't think the serial# behaviour has changed, only the way of building the list.

`existing_serials = existing_serials + apps`

will have been creating a new list each time, so wouldn't suffer this issue.

I've got Echo Dots, Echo Shows, Sonos, Fire TV sticks, and Alexa Mobile Voice iOS devices in the list. One of those is probably projecting an appDeviceList which has a serial that is then self-referencing.

I added logging to confirm that the issue is definitely within this loop. I can easily replicate it (happens every time). It is also resolved with this change.

**Comment by alandtse** [comment]
Thanks!

**Comment by jleinenbach** [comment]
I just want to say sorry that I was unable to fix it fast. I tested the version, but not long enough as it seems. I am still trying to improve the code, but I will test it much longer now!

**Pull request merged**
