### PR TITLE
revert: __init__.py

### PR DESCRIPTION
**Pull request by ChristophCaina**
revert last changes back, as they are causing another chain of errors :-(

### CODE REVIEW

**Comment by danielbrunt57** [comment]
Hi @ChristophCaina,
Recently I solved this in my live system with `from homeassistant.components import persistent_notification`.
My current live system which has no errors (at the moment!) has neither this or yours but you might want to give it a try...

**Comment by danielbrunt57** [comment]
BTW, for the last 10-12 hours or so I've been devising a scheme to  update `last_alexa` in a timely fashion (less than 2 seconds!) since the recent demise of Amazon's http2 `PUSH_ACTIVITY` command (which I've found zero documentation on after countless hours searching) rendered it virtually useless...

**Comment by ChristophCaina** [comment]
Hi,
I would give it a try. Sure.

At the Moment, each Change will cause another Error somewhere else.

I got the deprication for __ini__.py solved, but then another in config_flow.py was shown.

And still, even with a rollback to 4.12.1 the Integration is Not working with HA 2024.8.0b0 - I have to Take this into Account during my tests 🫣

I also tried to bump my alexapy to the most recent Version, but this doesn't Change much...

Worst Case: all effort is obsolete next wednesday.

**Comment by danielbrunt57** [comment]
I edited the title for you.  It's pretty picky and wants it start with `fix:`, `revert`, `chore:`, etc...

**Comment by danielbrunt57** [comment]
> [EDIT]
> 
> The new deprecation I am having in the logs:
> 
> ```
> 2024-08-02 10:20:40.214 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification.
> 
> This is deprecated and will stop working in Home Assistant 2024.9,
> it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/config_flow.py, line 680:
> self.hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_
> ```

Is that with `from homeassistant.components import persistent_notification`?

**Comment by danielbrunt57** [comment]
> Worst Case: all effort is obsolete next wednesday.

@petro31's comment to me was that the integration is horribly broken by 2024.8 and based on his comments re: aiohttp and alexapy, it's virtually irreparable...

**Comment by ChristophCaina** [comment]
> > [EDIT]
> > The new deprecation I am having in the logs:
> > ```
> > 2024-08-02 10:20:40.214 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification.
> > 
> > This is deprecated and will stop working in Home Assistant 2024.9,
> > it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/config_flow.py, line 680:
> > self.hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_
> > ```
> 
> Is that with `from homeassistant.components import persistent_notification`?

still testing it.
It was with other changes I've made.
But yes, just changing it in the __init__.py will still throw this error.
It was not shown in the log window of HA itself - but can be found in the logfile directly.

Yes, I am also in a discussion with them on discord.

**Comment by danielbrunt57** [comment]
> > > [EDIT]
> > > The new deprecation I am having in the logs:
> > > ```
> > > 2024-08-02 10:20:40.214 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification.
> > > 
> > > This is deprecated and will stop working in Home Assistant 2024.9,
> > > it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/config_flow.py, line 680:
> > > self.hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_
> > > ```
> > 
> > 
> > Is that with `from homeassistant.components import persistent_notification`?
> 
> still testing it. It was with other changes I've made. But yes, just changing it in the **init**.py will still throw this error. It was not shown in the log window of HA itself - but can be found in the logfile directly.
> 
> Yes, I am also in a discussion with them on discord.

I've just submitted a new PR to fix the deprecated hass components usage re : persistent_notification.
I styled it after a PR I found for the hacs integration addressing the same error.

**Comment by alandtse** [comment]
I assume this can be closed given the other PR.

**Pull request closed without merging**
