### PR TITLE
fix: fix deprecated hass.components use

### PR DESCRIPTION
**Pull request by danielbrunt57**
replace hass.components.persistent_notification.async_dismiss with async_diismiss_persistent_notification
addresses deprecated warning in issue in #2467

### CODE REVIEW

**Comment by alandtse** [comment]
Does this require a min HA bump?

**Comment by danielbrunt57** [comment]
> Does this require a min HA bump?

That is a good question...

**Comment by danielbrunt57** [comment]
> Does this require a min HA bump?

No.   homeassistant 2024.2.0 contains `async_create()` and `async_dismiss()`.

So why was this question not raised on PR [#2400](https://github.com/alandtse/alexa_media_player/pull/2400) for the same changes in  `__init__.py` and `config_flow.py`?

**Comment by alandtse** [comment]
Sometimes I forget.

**Comment by alandtse** [comment]
Oh also, if you're talking about what was reverted. You also just merged without waiting for approval. That's a bit hard for me to ask the question when you don't wait.

**Comment by danielbrunt57** [comment]
Ok, my mistake.  You authored #2400 to revert #2396 which I should not have merged!  The result now is config_flow.py needs this re-applied...

**Pull request merged**
