### PR TITLE
fix: add callback decorator to hide threading warning

### PR DESCRIPTION
**Pull request by danielbrunt57**
Fix issues #2306 and #2264 - error `alexa_media' calls hass.bus.async_fire from a thread other than the event loop` when alarms are dismissed or snoozed.

### CODE REVIEW

**Comment by danielbrunt57** [comment]
Alan, I'm not sure this is the correct fix as I can't tell if `def _process_raw_notifications(self):` is running in the event loop or the executor as I don't really understand how all that is done code-wise.  I understand the concept of threading but when I look at the code I'm not sure what's running where..

**Comment by alandtse** [comment]
Actually, this just lies to HA and says there's no synchronous calls. I don't think this is a true solution although it'll shut up the warning until they add another test.

**Comment by danielbrunt57** [comment]
Can I go ahead and merge it then?

**Comment by alandtse** [comment]
I don't think this is a solution. You're hiding the message by declaring a callback. It's not fixing it.

**Comment by danielbrunt57** [comment]
I had previously messaged Petro over in HACF and got his thoughts about `@callback` and `self.hass.bus.fire` vs `self.hass.bus.async_fire`.  Rather than duplicating it all here, can I add you into the conversation?

**Comment by alandtse** [comment]
I mean if you're positive this is the fix, then I'll trust you but last I checked `@callback` was just a decorator that doesn't change the underlying function.

**Comment by alandtse** [comment]
And honestly, any serious code discussions should be public so people understand why it was made.

**Comment by danielbrunt57** [comment]
I posted a topic in HACF but got zero responses.  I then messaged Petro and he responded.  His answer was in two parts:
[quote="petro, post:3, topic:753137, full:true"]
The callback one is more correct. I'm not 100% sure what callback does when going through the event bus, but it does hold special meaning. It basically adds a property to the coroutine that the event bus does something specific with.
[/quote]
[quote]
The async_track_point_in_utc_time does that. Callback just adds a property to the function.
```
def callback[_CallableT: Callable[..., Any]](func: _CallableT) -> _CallableT:
    """Annotation to mark method as safe to call from within the event loop."""
    setattr(func, "_hass_callback", True)
    return func
```
I just checked the code, it allows the coroutine to be flagged as a HassJob, which lets HA know it’s safe to call within the event loop.
[/quote]

I'm not sure how else to go public with it?

I tested dismissing an alarm both with it running in executor code using `self.hass.bus.async_fire` and again with it running in the event loop via `self.hass.bus.async_fire` decorated with `@callback` and both solutions worked without an error.  If you'd like to keep it in executor code rather than event loop, I'm fine with that.  I've found other integrations with the error and one fixed it with `@callback` and `self.hass.bus.async_fire` and another fixed it with `hass.bus.fire`.  I don't really know if one is more correct than the other...

**Comment by alandtse** [comment]
Honestly, we lived without the warning for years before HA found a reason to detect it. I guess we can go a few more years.

**Comment by danielbrunt57** [comment]
So @callback is kind of like saying "Trust me, this routine is perfectly safe so go ahead and put it in the event loop!"??

**Comment by alandtse** [comment]
Yes.

**Comment by alandtse** [comment]
At least that's how I understood it. It's been years since I checked it's implementation.

**Comment by Petro31** [comment]
> I posted a topic in HACF but got zero responses. I then messaged Petro and he responded. His answer was in two parts: [quote="petro, post:3, topic:753137, full:true"] The callback one is more correct. I'm not 100% sure what callback does when going through the event bus, but it does hold special meaning. It basically adds a property to the coroutine that the event bus does something specific with. [/quote] [quote] The async_track_point_in_utc_time does that. Callback just adds a property to the function.
> 
> ```
> def callback[_CallableT: Callable[..., Any]](func: _CallableT) -> _CallableT:
>     """Annotation to mark method as safe to call from within the event loop."""
>     setattr(func, "_hass_callback", True)
>     return func
> ```
> 
> I just checked the code, it allows the coroutine to be flagged as a HassJob, which lets HA know it’s safe to call within the event loop. [/quote]
> 
> I'm not sure how else to go public with it?
> 
> I tested dismissing an alarm both with it running in executor code using `self.hass.bus.async_fire` and again with it running in the event loop via `self.hass.bus.async_fire` decorated with `@callback` and both solutions worked without an error. If you'd like to keep it in executor code rather than event loop, I'm fine with that. I've found other integrations with the error and one fixed it with `@callback` and `self.hass.bus.async_fire` and another fixed it with `hass.bus.fire`. I don't really know if one is more correct than the other...

I was under the impression that you moved to `hass.bus.fire` while marking it as a `callback`, if that's not the case, then this PR is not correct.  `has.bus.fire` is the correct path.

**Pull request merged**
