### PR TITLE
fix: use dict.get for OptionsFlow handler

### PR DESCRIPTION
**Pull request by danielbrunt57**
fix: Changed OptionsFlow handler to incorporate a dictionary to permit a 'get' with fixed default values when config entry was created pre v4.11.0 and is missing the new saved fields.

### CODE REVIEW

**Comment by alandtse** [comment]
Is their an issue you're closing? Also, the PR should explain what changed. See https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by danielbrunt57** [comment]
> Is their an issue you're closing? Also, the PR should explain what changed.

I've edited the title and first comment.  Satisfactory?

**Comment by alandtse** [comment]
Thanks. Note the changes.

**Comment by danielbrunt57** [comment]
How do you get this...
image

to display as...
image

**Comment by alandtse** [comment]
Uh, it's literally the PR #.

**Comment by danielbrunt57** [comment]
> Uh, it's literally the PR #. All PRs numbers are appended by Github.

Got it.  It's so close to the issue (#2323) I was thinking it was that

**Pull request merged**
