### PR TITLE
fix: bump alexapy to 1.28.2

### LINKED ISSUE #2433: Broken Home Assistant Configuration in HAss Core 2024.8.0
**Describe the bug**

Devices unresponsive under any circumstance, HA asking to reconfigure the extension but nothing happens. 

**To Reproduce**

1. Update Home Assistant Core to version 2024.8.0. 
2. Check the settings under devices and settings.
3. Click on Alexa Media Player, check that the integration is working (it's not).
4. See the error, Home Assistant asks to reconfigure the integration.

**Expected behavior**

The integration to properly work as it did before updating HAss Core to 2024.8.0. 
To show all my echo devices as well as Alexa linked ones.

**Screenshots**

The UI Error is shown below:
Screenshot 2024-08-08 alle 15 35 14

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup): 4.12.6
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled]: Yes

**Logs**

Don't know where to find them! Tried to take a look to the log files but nothing seems to be relevant...

**Additional context**

### PR DESCRIPTION
**Pull request by chrisvblemos**
Critical to fix all issues related to nom .com domains.

Fixes #2433, #2430, #2429, #2427, #2426, #2418, #2407

### CODE REVIEW

**Comment by chrisvblemos** [comment]
pre-commit.ci autofix

**Comment by alandtse** [comment]
Can you please check the dev container for other users of alexapy? You can text search the repo or look at other bumps. I believe there are two more places for the bump.

**Comment by chrisvblemos** [comment]
Fixes #2427, #2433, #2418, #2407, #2426, #2429.

**Comment by chrisvblemos** [comment]
> Can you please check the dev container for other users of alexapy? You can text search the repo or look at other bumps. I believe there are two more places for the bump.

Done. Don't know why the change wasn't initially commited. Mea culpa for not checking the diffs. Checked other bumps, don't think anything is missing other than bumping python to 3.11. Let me know if you still think there is something missing.

**Comment by jleinenbach** [comment]
Sorry, I did the same to the same time and didn't see this PR. But I had to go up to Python 3.12 because of build issues.

**Comment by chrisvblemos** [comment]
Added changes to devcontainer/Dockerfile. Project is now buildable using devcontainer, tested locally. Thanks to @jleinenbach for the suggestion. There are a few differences from your initial approach to better comply with recommendations, and it is working with python 3.11.

Ready for review @alandtse .

**Comment by danielbrunt57** [comment]
@chrisvblemos Can we now bump alexapy to 1.29.0?

**Pull request merged**
