### PR TITLE
fix: delete cookiefile when removing config entry

### PR DESCRIPTION
**Pull request by danielbrunt57**
Delete pickle file when removing config entry as it's no longer needed and can cause issues when re-adding the integration entry.

### CODE REVIEW

**Comment by alandtse** [comment]
Can you confirm the file isn't handled at the alexapy level? If so, any deletion should be handled there via an API call.

**Comment by danielbrunt57** [comment]
No, it's not and it always gets left behind when the config entry is removed and has caused issues galore for a little while now for users trying to fix other setup issues..
I added it to `async def async_unload_entry` (line 1289) where everything but it gets removed when the config entry is deleted and felt that was the appropriate place.
Please review and advise...

**Comment by danielbrunt57** [comment]
Even with a working setup, you can delete the pickle file, restart and it re-authenticates and re-creates the pickle file and continues merrily along...

**Comment by danielbrunt57** [comment]
The only reference in alexapy to the pickle file is in alexalogin.py:

`def __init__(`
```
        self._cookiefile: list[str] = [
            self._outputpath(f".storage/{self._hass_domain}.{self.email}.pickle"),
            self._outputpath(f"{self._hass_domain}.{self.email}.pickle"),
            self._outputpath(f".storage/{self._hass_domain}.{self.email}.txt"),
        ]
```
and this:
```
    async def save_cookiefile(self) -> None:
        """Save login session cookies to file."""
        self._cookiefile = [
            self._outputpath(f".storage/{self._hass_domain}.{self.email}.pickle"),
            self._outputpath(f"{self._hass_domain}.{self.email}.pickle"),
            self._outputpath(f".storage/{self._hass_domain}.{self.email}.txt"),
        ]
        for cookiefile in self._cookiefile:
            if cookiefile == self._cookiefile[0]:
                cookie_jar = self._session.cookie_jar
                assert isinstance(cookie_jar, aiohttp.CookieJar)
                if self._debug:
                    _LOGGER.debug("Saving cookie to %s", cookiefile)
                try:
                    cookie_jar.save(self._cookiefile[0])
                except (OSError, EOFError, TypeError, AttributeError) as ex:
                    _LOGGER.debug(
                        "Error saving pickled cookie to %s: %s",
                        self._cookiefile[0],
                        EXCEPTION_TEMPLATE.format(type(ex).__name__, ex.args),
                    )
            elif (cookiefile) and os.path.exists(cookiefile):
                _LOGGER.debug("Removing outdated cookiefile %s", cookiefile)
                await delete_cookie(cookiefile)
        if self._debug:
            _LOGGER.debug("Session Cookies:\n%s", self._print_session_cookies())
```

**Comment by alandtse** [comment]
Then you should create a delete_cookiefile in alexapy and then call that in amp.

**Comment by danielbrunt57** [comment]
Something like this then?

image

image

> 2024-08-17 16:37:38.560 DEBUG (MainThread) [alexapy.alexaapi] d****l@b******a: Trying post: https://alexa.amazon.com/api/behaviors/preview : with uri: /api/behaviors/preview data {'behaviorId': 'PREVIEW', 'sequenceJson': '{"@type": "com.amazon.alexa.behaviors.model.Sequence", "startNode": {"@type": "com.amazon.alexa.behaviors.model.SerialNode", "nodesToExecute": [{"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode", "type": "Alexa.Speak", "operationPayload": {"deviceType": "A2U21SRK4QGSE1", "deviceSerialNumber": "G091AA08051216SA", "locale": "en-ca", "customerId": "A1UZ93DGNU3F5L", "textToSpeak": "Home Assistant startup is complete", "target": {"customerId": "A1UZ93DGNU3F5L", "devices": [{"deviceSerialNumber": "G091AA08051216SA", "deviceTypeId": "A2U21SRK4QGSE1"}]}, "skillId": "amzn1.ask.1p.saysomething"}}]}}', 'status': 'ENABLED'} query None
> 2024-08-17 16:37:38.676 DEBUG (MainThread) [alexapy.alexaapi] d****l@b******a: POST: https://alexa.amazon.com/api/behaviors/preview returned 200:OK:application/octet-stream
> 2024-08-17 16:39:42.804 DEBUG (MainThread) [alexapy.helpers] Deleting cookiefile /config/.storage/alexa_media.daniel@brunt.ca.pickle

image

**Comment by danielbrunt57** [comment]
Wait a minute!  There's already a helper...

> 2024-08-17 16:39:42.804 DEBUG (MainThread) [alexapy.helpers] Deleting cookiefile /config/.storage/alexa_media.daniel@brunt.ca.pickle

So why wasn't it working??

**Comment by danielbrunt57** [comment]
Note: this fix requires alexapy merge request !380

**Comment by alandtse** [comment]
So what was the deal before for why it was failing?

**Comment by danielbrunt57** [comment]
When I first saw the alexapy helper at work, I was slightly confused/mislead by it but then I realized that my code addition in alexapy is actually using that helper, which is used elsewhere in alexapy, but there was no code in alexapy that AMP's `async def async_unload_entry()` could call, and I don't think I could have called the helper directly from AMP.

**Comment by danielbrunt57** [comment]
I see you've been busy!  What about the underlying requirement in alexapy?  v4.12.8 will need a new alexapy (==1.28.3?) to be able to delete the cookiefile...

**Comment by alandtse** [comment]
I mean if it required a version bump it should've been in the PR. Please only submit complete PRs. I don't have time to guess if it needs more parts to it.

**Comment by alandtse** [comment]
Please mark it as a Draft if it's incomplete.

**Comment by danielbrunt57** [comment]
> I mean if it required a version bump it should've been in the PR.

Forgive me for still being quite new to this PR stuff and not knowing everything yet but I do not know how or where that would be specified.  I did add comment `Note: this fix requires alexapy merge request !380` 8 hours ago but I guess you're too busy to have seen that...

**Comment by chrisvblemos** [comment]
In these cases, I suggest you first submit the PR to AlexaPy and then only after AlexaPy has your PR merged you submit the PR here, including the bump in AlexaPy's version. Might take some time, given alandtse free time, but it is the safest way.

**Comment by danielbrunt57** [comment]
@chrisvblemos 
Yes, I can see now after-the-fact that I did it incorrectly but thank you for pointing out my mistake!
Perhaps v4.12.8 can be pulled to prevent more reports of an error that have already started to appeared in AMP issues.  See Voice notifications[ #2442](https://github.com/alandtse/alexa_media_player/issues/2442#issuecomment-2295300581) ...

**Comment by danielbrunt57** [comment]
I've added a [new isssue](https://github.com/alandtse/alexa_media_player/issues/2470) with how to eliminate the error for now...

**Comment by danielbrunt57** [comment]
New [PR #2471](https://github.com/alandtse/alexa_media_player/pull/2471) submitted to check if AlexaLogin.delete_cookiefile exists before trying to call it.

**Pull request merged**
