### PR TITLE
chore: release 2024-10-05

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Comment by alandtse** [comment]
Before I do this merge, I'm going to need a few approvals from people testing the dev build.

**Comment by alandtse** [comment]
Looks like HACS has removed the ability to always pull the default branch, in this case dev. Not sure what's the easy way to test, but hopefully people figure it out and report back.

**Comment by Esiravegna** [comment]
I just cloned the branch and overwritted the alexa_media folder in my custom folder, I will let you know on the results.

**Comment by Esiravegna** [comment]
So far, 24 hours since I manually installed this branch into my custom_components, no issues to report.

**Comment by alandtse** [comment]
Thanks for confirming.

**Pull request merged**
