### PR TITLE
fix: Reorder `restore_volume` key/value pairs

### PR DESCRIPTION
**Pull request by danielbrunt57**
Change order of `restore_volume` key/value pairs  in `strings.json`.
Duplicate `strings.json` to `en.json`.

### CODE REVIEW

**Comment by alandtse** [comment]
Did you confirm hassfest is ok with these changes? Or are you just guessing?

**Comment by danielbrunt57** [comment]
[Validate / ci (pull_request)](https://github.com/alandtse/alexa_media_player/actions/runs/12553629544/job/35001278648?pr=2781)Successful in 44s:
```
13s
Run home-assistant/actions/hassfest@master
Run echo "::add-matcher::/home/runner/work/_actions/home-assistant/actions/master/hassfest/problem-matcher.json"
Run docker run --rm -v /home/runner/work/alexa_media_player/alexa_media_player://github/workspace ghcr.io/home-assistant/hassfest
Unable to find image 'ghcr.io/home-assistant/hassfest:latest' locally
latest: Pulling from home-assistant/hassfest
38a83[1](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806#step:7:1)0d387e: Already exists
c5e459a2f580: Pulling fs layer
1bedd1d1e9[5](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806#step:7:6)6: Pulling fs layer
bca16dc4b45b: Pulling fs layer
a2114b2a126c: Pulling fs layer
73cc04ddbd4f: Pulling fs layer
f00ca1da2ad5: Pulling fs layer
73cc04ddbd4f: Waiting
f00ca1da2ad5: Waiting
a2[11](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806#step:7:13)4b2a126c: Waiting
bca16dc4b45b: Download complete
c5e459a2f580: Verifying Checksum
c5e459a2f580: Download complete
a2114b2a126c: Download complete
1bedd1d1e956: Verifying Checksum
1bedd1d1e956: Download complete
73cc04ddbd4f: Verifying Checksum
73cc04ddbd4f: Download complete
c5e459a2f580: Pull complete
f00ca1da2ad5: Verifying Checksum
f00ca1da2ad5: Download complete
1bedd1d1e956: Pull complete
bca16dc4b45b: Pull complete
a[21](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806#step:7:24)14b2a126c: Pull complete
73cc04ddbd4f: Pull complete
f00ca1da2ad5: Pull complete
Digest: sha256:ad6d35b9a010d493c098f7e068bd7baa1beeed40658bc89de1e60ada80d5dece
Status: Downloaded newer image for ghcr.io/home-assistant/hassfest:latest
Error loading libturbojpeg; Camera snapshot performance will be sub-optimal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/camera/img_util.py", line 100, in __init__
    TurboJPEGSingleton.__instance = TurboJPEG()
                                    ~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/turbojpeg.py", line [30](https://github.com/alandtse/alexa_media_player/actions/runs/12524769225/job/34935630806#step:7:33)0, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/turbojpeg.py", line 967, in __find_turbojpeg
    raise RuntimeError(
    ...<2 lines>...
        'e.g. jpeg = TurboJPEG(lib_path)')
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
Validating application_credentials... done in 0.00s
Validating bluetooth... done in 0.00s
Validating codeowners... done in 0.00s
Validating config_schema... done in 0.01s
Validating dependencies... done in 0.15s
Validating dhcp... done in 0.00s
Validating icons... done in 0.00s
Validating json... done in 0.00s
Validating manifest... done in 0.00s
Validating mqtt... done in 0.00s
Validating quality_scale... done in 0.00s
Validating requirements... done in 0.00s
Validating services... done in 0.00s
Validating ssdp... done in 0.00s
Validating translations... done in 0.01s
Validating usb... done in 0.00s
Validating zeroconf... done in 0.00s
Validating config_flow... done in 0.00s

Integrations: 1
Invalid integrations: 0
```

**Comment by danielbrunt57** [comment]
But the above is the same as when I submitted the previous merged PR.
See https://github.com/alandtse/alexa_media_player/actions/runs/12500877167/job/34877608221

**Comment by alandtse** [comment]
Did you update the keys in lokalise? En.json is overwritten from lokalise.

**Comment by danielbrunt57** [comment]
> Did you update the keys in lokalise? En.json is overwritten from lokalise.

No, and I can't figure out how to do that.  It says I am a contributor to the project and I watched a help video which says to click the upload button in the project but I cannot find a screen that looks like the one in their help video!

image

**Comment by danielbrunt57** [comment]
image

**Comment by danielbrunt57** [comment]
I was able to create a new project "AMP" and uploaded the `strings.json` and can select all 54 keys and order a translation so I now see how the process should work but I do not seem to have the permissions to do the same in the "Alexa Media Player" project...

**Pull request merged**
