### PR TITLE
fix: use async_create for notification

### PR DESCRIPTION
**Pull request by ChristophCaina**
fixed issue with partition cookies
(https://gitlab.com/keatontaylor/alexapy/-/commit/e594a3b194eec7d6451ad0c7135d8c32704f5f73)

unfortunately, this change does not solve the issue #2378

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks. However a dependency bump requires changes in multiple places. Please take a look at past bumps to see what is required.

**Comment by ChristophCaina** [comment]
Thanks,
I will Check this.

**Comment by ChristophCaina** [comment]
should now also fix #2382 - but since my installation is not loading, I cannot test this further :-(

**Comment by alandtse** [comment]
Since the alexapy bump isn't complete, let's just do the persistent notification with this PR.

**Comment by ChristophCaina** [comment]
reverted the version bump back :)

**Pull request merged**
