### PR TITLE
revert: revert changes in v4.13.3

### PR DESCRIPTION
**Pull request by apbarratt**
Rolls back all changes to 4.13.2 and updates version numbers to 4.13.4

https://github.com/alandtse/alexa_media_player/issues/2586
https://github.com/alandtse/alexa_media_player/issues/2583
https://github.com/alandtse/alexa_media_player/issues/2579

### CODE REVIEW

**Comment by alandtse** [comment]
Not going to do a full revert of all commits. I pulled the release so we can figure out which specific commit caused it and target that.

Happy to leave this as the PR (to figure out which) or you can close it until we get a targeted one. Thanks!

**Comment by alandtse** [comment]
Went with #2589. Thanks again!

**Comment by apbarratt** [comment]
That's fair, glad to see lots of work going into a fix and post mortem. Let me know if you need some guinea pigs to test stuff :)

**Comment by PJLLB** [comment]
Thanks to the fixers out there!

**Pull request closed without merging**
